version: '3'

services:
  mailserver:
    image: tvial/docker-mailserver:latest
    container_name: mail
    hostname: mail
    domainname: example.com
    env_file: mailserver.env
    ports:
      - "25:25"
      - "587:587"
      - "143:143"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
    cap_add:
      - NET_ADMIN
    restart: always

  roundcube:
    build:
      context: ./php-fpm # Đường dẫn đến thư mục chứa Dockerfile và xdebug.ini
      dockerfile: Dockerfile
    container_name: roundcube
    ports:
      - "8000:80"
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: mail
      ROUNDCUBEMAIL_SMTP_SERVER: mail
      ROUNDCUBEMAIL_SMTP_PORT: 587
    volumes:
      - ./roundcubemail:/var/www/html
    depends_on:
      - mailserver
    restart: always

volumes:
  maildata:
  mailstate:
  maillogs:
